version: "3.9"

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: auctionsite-mysql
    restart: always
    environment:
      MYSQL_DATABASE: auction_site
      MYSQL_ROOT_PASSWORD: atthelastsecond
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build: .
    container_name: auctionsite-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/auction_site?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: atthelastsecond
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    volumes:
      - ./target:/app/target

volumes:
  db_data:
